#+title: RICE - Rice Is a Complex Enchantment
#+author: Peromage

#+begin_quote
> Keep ricing
#+end_quote

* About
This is a collection of my daily tool configurations.

* Get started
Simply use =install.sh= script to install supported configs.

#+begin_src shell
# List supported configs
$ ./install.sh

# Install configurations for applications
$ ./install.sh bash pwsh git tmux

# Install all
$ ./install.sh $(./install.sh)
#+end_src

To add a new config installation, put a =install.sh= script in the application's folder.

* Why not just use GNU Stow?
=stow= is really good.  However, sometimes applications might accidentally change the configurations then the repository would become dirty.

I like to have some flexibility to control how the installation behaves.  Also I find that in order to use =stow= the folder structure may become ugly (I have to keep the same hierarchy).  That's why I like to use my own scripts.

* Appendix: a list of CLI alternatives
- Better ~ls~: [[https://github.com/ogham/exa][exa]]
- Better ~cat~: [[https://github.com/sharkdp/bat][bat]]
- Better ~grep~: [[https://github.com/BurntSushi/ripgrep][ripgrep]]
- Better ~find~: [[https://github.com/junegunn/fzf][fzf]]
- Quick jump:
  - [[https://github.com/ajeetdsouza/zoxide][zoxide]]
  - [[https://github.com/skywind3000/z.lua][z.lua]]
- File manager:
  - [[https://github.com/gokcehan/lf][lf]]
  - [[https://midnight-commander.org][mc]]
- Automation: [[https://github.com/eradman/entr][entr]]
