#+title: RICE - Rice Is Complex Enchantment
#+author: Peromage

#+begin_quote
> Keep ricing
#+end_quote

* About
This is a configuration collection of my daily drivers.

[[./config][config]] directory contains all the configurations.  They are organized in a way that how they are located in the actual home directory, so each of them can be managed by =stow= individually.

[[./bin][bin]] directory contains scripts and small executables which I use most of the times.

Directories that starts with =PRESET-= are the combinations I use often for different scenarios.  They can be managed by =stow= directly.

* Get started
All the configurations are managed by GNU =stow=.

Use the script [[./stow.sh][stow.sh]] to quickly manage presets.

#+begin_src shell
# Stow
./stow -S PRESET-general
./stow --stow PRESET-general

# Unstow
./stow -D PRESET-general
./stow --delete PRESET-general

# Restow
./stow -R PRESET-general
./stow --restow PRESET-general
#+end_src

* Appendix
** Fcitx5 with Rime
Customization should go into =name.custom.yaml= in order to avoid overwrite from redeployment.  For example, =~/.config/share/fcitx5/rime/default.yaml=, the corresponding customization file is =~/.config/share/fcitx5/rime/default.custom.yaml=.

To redeploy (rebuild), run
#+begin_src sh
fcitx5 -r
#+end_src

NOTE: In Gnome, ~super+space~ is eatten by mutter.  Need to find a workaround to enable it by users or simply use a different key binding like ~Ctrl+|~ (a mnemonic key corresponding to Emacs's ~Ctrl+\~).

** Common CLI alternatives
- Better =ls=: [[https://github.com/ogham/exa][exa]]
- Better =cat=: [[https://github.com/sharkdp/bat][bat]]
- Better =grep=: [[https://github.com/BurntSushi/ripgrep][ripgrep]]
- Better =find=: [[https://github.com/junegunn/fzf][fzf]]
- Quick jump: [[https://github.com/ajeetdsouza/zoxide][zoxide]], [[https://github.com/skywind3000/z.lua][z.lua]]
- File manager: [[https://github.com/gokcehan/lf][lf]], [[https://midnight-commander.org][mc]]
- Automation: [[https://github.com/eradman/entr][entr]]
