* PEW - Peromage's Emacs Workbench

#+begin_quote
A minimalist's Emacs configuration.
#+end_quote

This is my personal Emacs configuration. Be aware that it might not fit your needs.

This configuration intends to be as minimal as possible meaning that it prefers to use Emacs built-in features and optimize them.

Additionally, for convenience, I included my config collection for other apps in this repo. They can be found in =rice= directory which is managed by ~git subtree~.

** Features

- Light and quick
- Terminal friendly
- Respect Emacs vanilla key bindings
- Evil mode as the main editing mode (not every buffer)
- Vertico and its complementary packages as the completion framework
- LSP support

** Get Started

Clone this repo and put it to your home directory with folder name =.emacs.d=.

#+begin_src shell
git clone https://github.com/peromage/pew.git ~/.emacs.d
#+end_src

Then Emacs will automatically install everything for you.

*** Local Files

Temporary local changes can go into =pew/local.el= including settings by ~customize~.

=local.el= will be applied on top of the default pew configuration.

*** List of files and directories

#+begin_example
pew
├── lisp/                   # Configuration files
├── site-lisp/              # Addtional package files written by myself
├── yasnippets/             # Snippet files loaded by yasnippet
├── rice/                   # My config collection for other apps
├── early-init.el           # Init file loaded before init.el
├── init.el                 # Main init file
├── .pew                    # Configuration root placeholder
├── .gitignore              # Git ignore-file
├── LICENSE                 # License file
└── README.md               # This file
#+end_example

** Philosophy
*** Literal Configuration?

No.

Literal programming is a fantastic idea. However, I found that it's a distraction when I read my configuration code because I don't need to explain what I thought to myself.

In general, I believe I've left enough comments in my code at some places where it becomes difficult to understand whenever I go back after a while. My configuration is designed in a modular way and each module is descriptive by its name. Comments are also sectioned with outline format. So browsing and modifying the configuration should be easy.

Also literal configuration is a bit hard to debug and test since it has to be tangled each time it's updated. I know I can add hooks to do that automatically but I'm not a big fan of it. When I need my config I just need to clone it and fire up. That's what I need.

Don't forget that in the modular configuration I can add tool packages anytime under =site-list= directory. It might be a hassle if I use literal configuration in one file.

In one word, I prefer to use literal programming when I share snippets or posts but not my day-to-day configuration.

** Acknowledgement

This configuration is inspired by
- [[https://github.com/purcell/emacs.d][purcell/emacs.d]]
- [[https://protesilaos.com/emacs/dotemacs][Protesilaos Stavrou]]
- [[https://github.com/condy0919/.emacs.d][condy0919/.emacs.d]]
