* PEW - Peromage's Emacs Workbench

#+begin_quote
A minimalist's Emacs configuration.
#+end_quote

This is my personal Emacs configuration. Be aware that it might not fit your needs.

This configuration intends to be as minimal as possible meaning that it prefers to use Emacs built-in features and optimize them.

Additionally, for convenience, I included my config collection for other apps in this repo. They can be found in =rice= directory which is managed by ~git subtree~.

** Features

- Light and quick
- Terminal friendly
- Respect Emacs vanilla key bindings
- Evil mode as the main editing mode (not every buffer)
- Vertico and its complementary packages as the completion framework
- LSP support

** Get Started

Clone this repo and put it to your home directory with folder name =.emacs.d=.

#+begin_src shell
git clone https://github.com/peromage/pew.git ~/.emacs.d
#+end_src

Then Emacs will automatically install everything for you.

*** Local Files

Temporary local changes can go into =pew/local.el= including settings by ~customize~.

=local.el= will be applied on top of the default pew configuration.

*** List of files and directories

#+begin_example
pew
├── lisp/                   # Configuration files
├── site-lisp/              # Addtional package files written by myself
├── yasnippets/             # Snippet files loaded by yasnippet
├── rice/                   # My config collection for other apps
├── early-init.el           # Init file loaded before init.el
├── init.el                 # Main init file
├── .pew                    # Configuration root placeholder
├── .gitignore              # Git ignore-file
├── LICENSE                 # License file
└── README.md               # This file
#+end_example

** Acknowledgement

This configuration is inspired by
- [[https://github.com/purcell/emacs.d][purcell/emacs.d]]
- [[https://protesilaos.com/emacs/dotemacs][Protesilaos Stavrou]]
- [[https://github.com/condy0919/.emacs.d][condy0919/.emacs.d]]
